### ISSUE TITLE
Can't type savenames or unitnames or anything at all

### ISSUE THREAD

**Issue by Lowdive** [spring1944/Scenario-Editor-S44#2]
can't edit unit properties either, etc.
when I click the textboxes the typing cursor shows, but all keyboard input is ignored...

**Comment by kanatohodets** [comment]
@Lowdive Lowdive: gajop identified that we're relying on an old widgetHandler; I'll upgrade this in S44 tonight or tomorrow, which should fix (at least) this issue.

**Comment by ashdnazg** [comment]
Should work after https://github.com/spring1944/spring1944/commit/b0ef09243c8b9191b573b2118f7b72523951343b

**Comment by Lowdive** [comment]
it does, this is so cool, I can do stuff, then quit, then resume, then play
it on the run, then stop playing it, then edit again, then fix this and
that... and name units... and I haven't even tried triggers and stuff.

Do you know if there's a way to turn off the gridlines that show up when
placing units? because currently they lag my laptop to death, making
placement of units a li'l slow and tedious.

On Thu, Jul 16, 2015 at 5:43 AM, Eshed notifications@github.com wrote:

> Should work after spring1944/spring1944@b0ef092
> https://github.com/spring1944/spring1944/commit/b0ef09243c8b9191b573b2118f7b72523951343b
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/spring1944/Scenario-Editor-S44/issues/2#issuecomment-121923348
> .

## 

José Elí Santiago Rodríguez.
Disponibilidad de Horario.
https://www.google.com/calendar/embed?src=elisantiago.4e%40gmail.com&ctz=America/Mexico_City&mode=Week

**Comment by ashdnazg** [comment]
@Lowdive https://github.com/spring1944/Scenario-Editor-S44/commit/467d1f8481612dc254866a4978e5012fb309a8a3
