### ISSUE TITLE
Even with teams set as enemies, units won't shoot at each other.

### ISSUE THREAD

**Issue by Lowdive** [spring1944/Scenario-Editor-S44#4]
I've got team yellow team0 "US" trying to shoot at team blue team1 "GER" units, they just look at each other never shooting, we're talking about riflemen...
Using a saved scenario and a live scenario and spring version 100, though I don't know what spring1944 dev version was it...
(this didn't happen in previous engine version)

**Comment by kanatohodets** [comment]
ok, well, part of it is that units are being set to neutral, but even with that disabled they still can't fire. morph is also busted. further digging needed!

**Comment by kanatohodets** [comment]
Found it! Something is setting command / logistics to -10 billion. Nothing can fire because 0 > -10 billion, so there isn't enough resource to fire. I just pushed a commit to S44-scened to fix this.

**Comment by Lowdive** [comment]
nice!
