### ISSUE TITLE
When attempting to edit map texture

### ISSUE THREAD

**Issue by Lowdive** [spring1944/Scenario-Editor-S44#8]
picking any size or type of brush, with "any" texture (I tried about 4 from different folders, not all of them) I get this error when trying to "paint":
[f=0000891] Fragment shader failed to compile with the following errors:
ERROR: 0:33: error(#164) l-value required: assign "featureFactor" (can't modify a uniform)
ERROR: error(#273) 1 compilation errors.  No code generated

[f=0000891] [string "scen_edit/command/widget_terrain_change_tex..."]:196: attempt to index local 'shaderObj' (a nil value)
[f=0001144] Fragment shader failed to compile with the following errors:
ERROR: 0:33: error(#164) l-value required: assign "featureFactor" (can't modify a uniform)
ERROR: error(#273) 1 compilation errors.  No code generated

**Comment by gajop** [comment]
Map editing is in the process of a major upgrade, I advise you give it a go once it's done (or at least ready for testing).
It features new things such as brush editing, blur, void maps, specular+normal editing and more!

That said this error of yours gives me enough info to hopefully fix the error for the future. It seems like my (Nvidia) GFX card is more flexible with allowing GLSL uniforms to be modified (they're supposed to stay const it seems), and yours isn't, hence the problem. Anyway, easily fixed!

**Comment by Lowdive** [comment]
Nice!

On Thu, Jan 7, 2016 at 11:54 AM, Gajo Petrovic notifications@github.com
wrote:

> Map editing is in the process of a major upgrade, I advise you give it a
> go once it's done (or at least ready for testing).
> It features new things such as brush editing, blur, void maps,
> specular+normal editing and more!
> 
> That said this error of yours gives me enough info to hopefully fix the
> error for the future. It seems like my (Nvidia) GFX card is more flexible
> with allowing GLSL uniforms to be modified (they're supposed to stay const
> it seems), and yours isn't, hence the problem. Anyway, easily fixed!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/spring1944/Scenario-Editor-S44/issues/8#issuecomment-169755865
> .

## 

José Elí Santiago Rodríguez.
Disponibilidad de Horario.
https://www.google.com/calendar/embed?src=elisantiago.4e%40gmail.com&ctz=America/Mexico_City&mode=Week

**Comment by gajop** [comment]
This should be fixed in the latest develop version
